### ISSUE TITLE
[FEATURE] View Resume Functionality

### ISSUE THREAD

**Issue by kaustubhgupta** [kaustubhgupta/PortfolioFy#13]
An optional section, "View Resume" Needs to be added to all levels. The heading will be "View Resume" and it would hyperlink to the Google Drive/overleaf or any other link user passes in the GitHub Action

**Comment by ShivangiRai1310** [comment]
Could I work on this issue under SWOC?

**Comment by kaustubhgupta** [comment]
@ShivangiRai1310 Okay, you can work on this but do you have some knowledge of Python?

**Comment by kaustubhgupta** [comment]
Because the data flow for resume link from actions to data loaders is also needed. You can set up the HTML files by going through the wiki's https://github.com/kaustubhgupta/PortfolioFy/wiki/Setting-Up-Locally and after generating the HTML file, you can add the resume functionality.

**Comment by kaustubhgupta** [comment]
@ShivangiRai1310 Are you working on this? Let me know if you face any issues!

**Comment by ShivangiRai1310** [comment]
I have included the frontend part displaying the view resume upon clicking which the pdf opens in another window.
For now, in order to get the resume, I have added a random google drive uploaded link which can be fetched from command line input properties, in case required that way.

Otherwise, let me know how else should I fetch the link. Could you elaborate on that "resume link from actions to data loaders needed"

![Screenshot (421)](https://user-images.githubusercontent.com/57129598/104236240-36fa8e00-547c-11eb-87cf-90b1247e126a.png)
![Screenshot (419)](https://user-images.githubusercontent.com/57129598/104236246-3a8e1500-547c-11eb-9deb-7dd09c1717eb.png)
![Screenshot (423)](https://user-images.githubusercontent.com/57129598/104236256-3e219c00-547c-11eb-908a-0552a90b6ec3.png)

**Comment by kaustubhgupta** [comment]
For getting the link from the user, create a new variable in actions.yml. See the existing parameters to get an idea of how to declare one. Basically, it is :
```yml
inputs:
  variable_name:
    description: "<Give the description for resume link, anything would work>"
    required: False
    default: None
```

After declaring it, pass it as:
![image](https://user-images.githubusercontent.com/43691873/104278666-f7a95d00-54ce-11eb-8322-c30b6899ba2d.png)
make it last argument.


After all this, you will be able to get the variable in the generate_index.py file. Store it in a variable and pass it to both levels and ultimately, using f-strings, pass it to your HTML.

**Comment by kaustubhgupta** [comment]
Are you able to test this parameter locally?

**Comment by ShivangiRai1310** [comment]
Please do add Swoc label before merging in case required.

**Comment by kaustubhgupta** [comment]
@ShivangiRai1310 That's not an issue 😃
